# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
User.destroy_all
City.destroy_all
Attraction.destroy_all
Trip.destroy_all


city1 = City.create(name: 'New York', image: 'NYC.jpg', info: "   Many districts and landmarks in New York City have become well known to the city's approximately 55 million annual visitors. Several sources have ranked New York the most photographed city in the world. Times Square, iconified as The Crossroads of the World, is the brightly illuminated hub of the Broadway Theater District, one of the world's busiest pedestrian intersections, and a major center of the world's entertainment industry. The names of many of the city's bridges, skyscrapers, and parks are known around the world. Providing continuous 24/7 service, the New York City Subway is one of the most extensive metro systems worldwide, with 468 stations in operation.")
city2 = City.create(name: 'Los Angeles', image: 'LA.jpg', info: "   Nicknamed the City of Angels, Los Angeles is a global city, with strengths in business, international trade, entertainment, culture, media, fashion, science, sports, technology, education, medicine and research. It has been ranked sixth in the Global Cities Index and 9th Global Economic Power Index. The city is home to renowned institutions covering a broad range of professional and cultural fields and is one of the most substantial economic engines within the United States. Los Angeles includes Hollywood and leads the world in the creation of television productions, video games, and recorded music; it is also one of the leaders in motion picture production. Additionally, Los Angeles hosted the Summer Olympic Games in 1932 and 1984.")
city3 = City.create(name: 'San Francisco', image: 'SF.jpg', info: "   San Francisco is a popular tourist destination, known for its cool summers, fog, steep rolling hills, eclectic mix of architecture, and landmarks including the Golden Gate Bridge, cable cars, the former prison on Alcatraz Island, and its Chinatown district. Although the Financial District, Union Square, and Fisherman's Wharf are well-known around the world, San Francisco is also characterized by its numerous culturally rich streetscapes featuring mixed-use neighborhoods anchored around central commercial corridors to which residents and visitors alike can walk. San Francisco is also the headquarters of five major banking institutions and various other companies such as the Gap Inc., Pacific Gas and Electric Company, Yelp, Pinterest, Twitter, Uber, Mozilla and Craigslist.")
city4 = City.create(name: 'Chicago', image: 'Chicago.jpg', info: "   In 2012, Chicago hosted 46.37 million international and domestic visitors, an overall visitation record. Chicago's culture includes contributions to the visual arts, novels, film, theater, especially improvisational comedy, and music, particularly jazz, blues, soul, and the creation of house music.  Upscale shopping along the Magnificent Mile and State Street, thousands of restaurants, as well as Chicago's eminent architecture, continue to draw tourists. The city is the United States' third-largest convention destination. The city has many nicknames, which reflect the impressions and opinions about historical and contemporary Chicago. The best-known include the Windy City and Second City. Chicago has professional sports teams in each of the major professional leagues.")
city5 = City.create(name: 'Washington DC', image: 'DC.jpg', info: "   The centers of all three branches of the federal government of the United States are in the District, including the Congress, President, and Supreme Court. Washington is home to many national monuments and museums, which are primarily situated on or around the National Mall. Washington, D.C., is a national center for the arts. The John F. Kennedy Center for the Performing Arts is home to the National Symphony Orchestra, the Washington National Opera, and the Washington Ballet. The city hosts 176 foreign embassies as well as the headquarters of many international organizations, trade unions, non-profit organizations, lobbying groups, and professional associations. Washington is one of 12 cities in the United States with teams from all four major professional men's sports and is home to one major professional women's team.")
city6 = City.create(name: 'Boston', image: 'Boston.jpg', info: "   One of the oldest cities in the United States, Boston was founded on the Shawmut Peninsula in 1630 by Puritan settlers from England. It was the scene of several key events of the American Revolution, such as the Boston Massacre, the Boston Tea Party, the Battle of Bunker Hill, and the Siege of Boston. Upon American independence from Great Britain, the city continued to be an important port and manufacturing hub, as well as a center for education and culture. Through land reclamation and municipal annexation, Boston has expanded beyond the original peninsula. Its rich history helps attract many tourists, with Faneuil Hall alone attracting over 20 million visitors. Boston's many firsts include the United States' first public school, Boston Latin School (1635), and first subway system (1897).")
city7 = City.create(name: 'Ottawa', image: 'Ottawa.jpg', info: "   Traditionally the ByWard Market (in Lower Town), Parliament Hill and the Golden Triangle (both in Centretown – Downtown) have been the focal points of the cultural scenes in Ottawa.[117] Modern thoroughfares such as Wellington Street, Rideau Street, Sussex Drive, Elgin Street, Bank Street, Somerset Street, Preston Street and Sparks Street are home to many boutiques, museums, theatres, galleries, landmarks and memorials in addition to eating establishments, cafes, bars and nightclubs. The city is also home to the Canada Agriculture Museum, the Canada Aviation and Space Museum, the Canada Science and Technology Museum, Billings Estate Museum, Bytown Museum, Canadian Museum of Contemporary Photography, Canadian Ski Museum, Currency Museum, and the Portrait Gallery of Canada.")
city8 = City.create(name: 'Montreal', image: 'Montreal.jpg', info: "   Montreal was referred to as Canada's Cultural Capital by Monocle magazine. The city is Canada's centre for French language television productions, radio, theatre, film, multimedia, and print publishing. Montreal's many cultural communities have given it a distinct local culture. A cultural heart of classical art and the venue for many summer festivals, the Place des Arts is a complex of different concert and theatre halls surrounding a large square in the eastern portion of downtown. Place des Arts has the headquarters of one of the world's foremost orchestras, the Montreal Symphony Orchestra. Nicknamed la ville aux cent clochers (the city of a hundred steeples), Montreal is renowned for its churches. ")
city9 = City.create(name: 'Toronto', image: 'Toronto.jpg', info: "   Toronto is the most populous city in Canada and the provincial capital of Ontario. The Royal Ontario Museum (ROM) is a museum of world culture and natural history. The Toronto Zoo,[59][60] is home to over 5,000 animals representing over 460 distinct species. The Art Gallery of Ontario contains a large collection of Canadian, European, African and contemporary artwork, and also plays host to exhibits from museums and galleries all over the world. The Don Valley Brick Works is a former industrial site, which opened in 1889, and was partly restored as a park and heritage site in 1996, with further restoration and reuse being completed in stages since then. City shopping area's include the Yorkville neighbourhood, Queen West, Harbourfront, the Entertainment District, the Financial District, and the St. Lawrence Market neighbourhood.")